name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-darwin-setup

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build app
        run: |
          mv Throne.app TRN.app

      - name: Publish app
        run: |
          echo 'Publishing TRN.app'
