name: TRN build matrix - macOS ARM64
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release Tag and version"
        required: true
      publish:
        description: "r for normal release, p for prerelease, leave empty to not publish anything"
        required: false
jobs:
  build-go:
    permissions:
      contents: read
    strategy:
      matrix:
        include:
          - cross_os: darwin
            cross_arch: arm64
            go_version: "1.25.9"
      fail-fast: false
    runs-on: macos-latest
    env:
      DEST: ${{ github.workspace }}/deployment/${{ matrix.cross_os }}-${{ matrix.cross_arch }}
    steps:
      - name: Checking out sources
        uses: actions/checkout@v4.2.2
      - name: Cache Common Download
        id: cache-common
        uses: actions/cache@v4.2.3
        with:
          path: artifacts.tgz
          key: CommonCache-${{ matrix.cross_os }}-${{ matrix.cross_arch }}-${{ hashFiles('script/build_go.sh', 'core/*') }}-${{ matrix.go_version }}
      - name: Install Golang
        if: steps.cache-common.outputs.cache-hit != 'true'
        uses: actions/setup-go@v5.5.0
        with:
          go-version: ${{ matrix.go_version }}
          cache-dependency-path: |
            core/server/go.sum
      - name: Install Protoc
        if: steps.cache-common.outputs.cache-hit != 'true'
        uses: arduino/setup-protoc@v3
        with:
          version: "31.1"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Installing protoc-gen-go
        if: steps.cache-common.outputs.cache-hit != 'true'
        run: |
          go install github.com/golang/protobuf/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
      - name: Build golang parts
        if: steps.cache-common.outputs.cache-hit != 'true'
        shell: bash
        run: |
          GOOS=${{ matrix.cross_os }} GOARCH=${{ matrix.cross_arch }} ./script/build_go.sh
      - name: Tar files
        if: steps.cache-common.outputs.cache-hit != 'true'
        run: tar czvf artifacts.tgz ./deployment
      - name: Uploading Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: TRN-${{ github.sha }}-Common-${{ matrix.cross_os }}-${{ matrix.cross_arch }}
          path: artifacts.tgz

  build-cpp:
    permissions:
      contents: read
    needs:
      - build-go
    strategy:
      matrix:
        include:
          - platform: macos-latest
            qt_version: "6.11.0"
            target: arm64
            dest_suffix: darwin-arm64
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      INPUT_VERSION: ${{ github.event.inputs.tag }}
      DEST: ${{ github.workspace }}/deployment/${{ matrix.dest_suffix }}
      DEST_SUFFIX: ${{ matrix.dest_suffix }}
      ARCH: ${{ matrix.target }}
    steps:
      - name: Checking out sources
        uses: actions/checkout@v4.2.2
        with:
          submodules: "recursive"
      - name: Download Artifacts
        uses: actions/download-artifact@v4.3.0
        with:
          path: download-artifact
      - name: Install Qt
        uses: jurplel/install-qt-action@v4.3.0
        with:
          version: ${{ matrix.qt_version }}
          setup-python: true
          cache: true
          cache-key-prefix: QtCache-${{ matrix.dest_suffix }}
      - name: macOS - Generate MakeFile and Build
        shell: bash
        run: |
          mkdir build
          cd build
          curl -fLso srslist.h "https://raw.githubusercontent.com/TRNproj/routeprofiles/rule-set/srslist.h"
          cmake -GNinja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DNKR_PACKAGE_MACOS=1 -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 -DCMAKE_OSX_ARCHITECTURES=${{ matrix.target }} ..
          ninja
          cd ..
          ./script/deploy_macos.sh
      - name: Tar files
        shell: bash
        run: tar czvf artifacts.tgz ./deployment
      - name: Uploading Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: TRN-${{ github.sha }}-${{ matrix.dest_suffix }}
          path: artifacts.tgz

  publish:
    name: Pack & Publish Release
    runs-on: ubuntu-latest
    needs:
      - build-cpp
    permissions:
      contents: write
      actions: read
    steps:
      - name: Checking out sources
        uses: actions/checkout@v4.2.2
      - name: Download Artifacts
        uses: actions/download-artifact@v4.3.0
        with:
          path: download-artifact
      - name: Pack
        run: |
          curl -Lo - https://github.com/tcnksm/ghr/releases/download/v0.17.0/ghr_v0.17.0_linux_amd64.tar.gz | tar xzv
          mv ghr*linux_amd64/ghr .
          find . -name artifacts.tgz | xargs -n1 tar xvzf
          cd deployment
          mkdir debug
          ####
          mkdir TRN
          mv darwin-arm64/TRN.app TRN/TRN.app
          mv TRN/TRN.app/Contents/MacOS/TRN.dSYM debug/TRN-${{ github.event.inputs.tag }}-macos-arm64.dSYM
          zip -9 --symlinks -r TRN-${{ github.event.inputs.tag }}-macos-arm64.zip TRN
          rm -rf darwin-arm64
          rm -rf TRN
          ####
          zip -9 -r debug-symbols.zip debug
      - name: Uploading Debug Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Debug-${{ github.sha }}
          path: deployment/debug-symbols.zip
      - name: Uploading Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Deployment-${{ github.sha }}
          path: deployment
      - name: PreRelease
        if: github.event.inputs.publish == 'p'
        run: |
          ./ghr -prerelease -delete -c ${{ github.sha }} -t "${{ github.token }}" -n "${{ github.event.inputs.tag }}" "${{ github.event.inputs.tag }}" deployment
      - name: Release
        if: github.event.inputs.publish == 'r'
        run: |
          ./ghr -delete -c ${{ github.sha }} -t "${{ github.token }}" -n "${{ github.event.inputs.tag }}" "${{ github.event.inputs.tag }}" deployment
